
name: GitGuardian Secret Scan

on:
  push:
  pull_request:

jobs:
  ggshield_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ggshield
        run: pip install ggshield

      - name: Authenticate ggshield
        env:
          GGSHIELD_API_KEY: ${{ secrets.GGSHIELD_API_KEY }}
        run: ggshield auth login --method token $GGSHIELD_API_KEY

      - name: Scan repository for secrets
        run: ggshield secret scan repo .
